name = "ComputerVisionMetrics"
uuid = "56beca70-ca20-45da-83c4-a042539b6c19"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.10"

[extras]
ImageDistances = "51556ac3-7006-55f5-8cb3-34580c88182d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ImageDistances", "Test"]
