name = "ComputerVisionMetrics"
uuid = "56beca70-ca20-45da-83c4-a042539b6c19"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "^1.7"
ImageMorphology = "^0.4.5"
StatsBase = "^0.34.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
